name: Release Charts

on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "hello world"
      - run: ls
  test-container:
    runs-on: self-hosted
    container: alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "hello world"
      - run: ls